### ISSUE TITLE
Missing name or value error

### ISSUE THREAD

**Issue by Silensea** [pjaselin/Cubist#115]
Hi,
I was trying to use Cubist to predict some properties, but catch this error:
```
CubistError: 
*** line 9305527 of `undefined.cases':
    missing name or value before `,'

Error limit exceeded
```
Is it related to my predictors' size (9331200* 19) or the dataframe format?

**Comment by pjaselin** [comment]
Hi @Silensea could you share a sample of your data? Maybe there are strings in your data or the column names are off?

**Comment by Silensea** [comment]
Sorry to reply too late.

**Comment by Silensea** [comment]
> Hi @Silensea could you share a sample of your data? Maybe there are strings in your data or the column names are off?

Sorry to reply late. The wrong line of my data as follows:
`
Longitude                                    -159.416667
Latitude                                       89.500000
CM_MANTLE_DEN_KGM3_CRUST1s.5m.ggg            3333.166504
GL_ACTIVE_VOLCANO_GVP.r50km.wct.5m.ggg          0.000000
GL_DIST_TO_COAST_KM_ETOPO.5m.ggg              735.008972
GL_DIST_TO_RIDGE_KM_PLATES.5m.ggg             378.662445
GL_DIST_TO_TRANSFORM_KM_PLATES.5m.ggg        5497.930664
GL_DIST_TO_TRENCH_KM_PLATES.5m.ggg           3356.435303
GL_TOT_SED_THICK_M_CRUST1_NOAA.5m.ggg        1300.000000
GL_TOT_SED_THICK_M_GLOBSED_Straume.5m.ggg    2252.011719
SC_CRUST_AGE_MA_Muller.5m.ggg                  48.444916
SC_CRUST_DEN_KGM3_CRUST1s.5m.ggg             2931.545654
SC_CRUST_THICK_M_CRUST1s.5m.ggg              7146.688477
SC_CRUST_VP_MS_CRUST1s.5m.ggg                6691.542480
SC_CRUST_VS_MS_CRUST1s.5m.ggg                3810.364746
SF_ACTIVE_SEAMOUNTS_KIM.r50km.wct.5m.ggg        0.000000
SF_DEEP_QUAKES_NCEDC.r50km.wct.5m.ggg           0.000000
SF_SHALLOW_QUAKES_NCEDC.r50km.wct.5m.ggg        0.000000
Name: 9305527, dtype: float64
`

**Comment by Silensea** [comment]
> Hi @Silensea could you share a sample of your data? Maybe there are strings in your data or the column names are off?
Sorry to reply late. My wrong line is as follows:
`
Longitude                                    -159.416667
Latitude                                       89.500000
CM_MANTLE_DEN_KGM3_CRUST1s.5m.ggg            3333.166504
GL_ACTIVE_VOLCANO_GVP.r50km.wct.5m.ggg          0.000000
GL_DIST_TO_COAST_KM_ETOPO.5m.ggg              735.008972
GL_DIST_TO_RIDGE_KM_PLATES.5m.ggg             378.662445
GL_DIST_TO_TRANSFORM_KM_PLATES.5m.ggg        5497.930664
GL_DIST_TO_TRENCH_KM_PLATES.5m.ggg           3356.435303
GL_TOT_SED_THICK_M_CRUST1_NOAA.5m.ggg        1300.000000
GL_TOT_SED_THICK_M_GLOBSED_Straume.5m.ggg    2252.011719
SC_CRUST_AGE_MA_Muller.5m.ggg                  48.444916
SC_CRUST_DEN_KGM3_CRUST1s.5m.ggg             2931.545654
SC_CRUST_THICK_M_CRUST1s.5m.ggg              7146.688477
SC_CRUST_VP_MS_CRUST1s.5m.ggg                6691.542480
SC_CRUST_VS_MS_CRUST1s.5m.ggg                3810.364746
SF_ACTIVE_SEAMOUNTS_KIM.r50km.wct.5m.ggg        0.000000
SF_DEEP_QUAKES_NCEDC.r50km.wct.5m.ggg           0.000000
SF_SHALLOW_QUAKES_NCEDC.r50km.wct.5m.ggg        0.000000
Name: 9305527, dtype: float64
`

**Comment by Silensea** [comment]
> Hi @Silensea could you share a sample of your data? Maybe there are strings in your data or the column names are off?

Sorry to reply late. My wrong line is as follows:
`
Longitude                                    -159.416667
Latitude                                       89.500000
CM_MANTLE_DEN_KGM3_CRUST1s.5m.ggg            3333.166504
GL_ACTIVE_VOLCANO_GVP.r50km.wct.5m.ggg          0.000000
GL_DIST_TO_COAST_KM_ETOPO.5m.ggg              735.008972
GL_DIST_TO_RIDGE_KM_PLATES.5m.ggg             378.662445
GL_DIST_TO_TRANSFORM_KM_PLATES.5m.ggg        5497.930664
GL_DIST_TO_TRENCH_KM_PLATES.5m.ggg           3356.435303
GL_TOT_SED_THICK_M_CRUST1_NOAA.5m.ggg        1300.000000
GL_TOT_SED_THICK_M_GLOBSED_Straume.5m.ggg    2252.011719
SC_CRUST_AGE_MA_Muller.5m.ggg                  48.444916
SC_CRUST_DEN_KGM3_CRUST1s.5m.ggg             2931.545654
SC_CRUST_THICK_M_CRUST1s.5m.ggg              7146.688477
SC_CRUST_VP_MS_CRUST1s.5m.ggg                6691.542480
SC_CRUST_VS_MS_CRUST1s.5m.ggg                3810.364746
SF_ACTIVE_SEAMOUNTS_KIM.r50km.wct.5m.ggg        0.000000
SF_DEEP_QUAKES_NCEDC.r50km.wct.5m.ggg           0.000000
SF_SHALLOW_QUAKES_NCEDC.r50km.wct.5m.ggg        0.000000
Name: 9305527, dtype: float64
`

**Comment by pjaselin** [comment]
Could you provide a sample of your code and the data? Unfortunately I don't think there's much I can do without a minimal working example.

**Comment by Silensea** [comment]
> 

Sorry, I'm late again. I forgot to check my notifications...
I have sorted out the code and data and they are about 300MB.
How can I make them available to you? Email? If possible, can you leave your email? I will send it to you as soon as possible.
Thank you very much for your help!

**Comment by Silensea** [comment]
> Could you provide a sample of your code and the data? Unfortunately I don't think there's much I can do without a minimal working example.

Sorry, I'm late again. I forgot to check my notifications...
I have sorted out the code and data and they are about 300MB.
How can I make them available to you? Email? If possible, can you leave your email? I will send it to you as soon as possible.
Thank you very much for your help!

**Comment by pjaselin** [comment]
@Silensea my apologies for the delay as well! I think you can attach files here, based on the text below: 
![image](https://user-images.githubusercontent.com/26674234/177048276-b97a3a08-5e8a-454d-962a-9674b74b12a9.png)
Otherwise how about creating a GitHub repo for it and I can check it out from there? If your data is publicly available I could grab it with any cleaning code you have if that also works.
