### ISSUE TITLE
Error Importing

### ISSUE THREAD

**Issue by piccolomo** [pjaselin/Cubist#117]
Hi,

I just installed the package, but I get:

![image](https://user-images.githubusercontent.com/56689657/220890386-6d10ddc5-97fa-4bbf-b745-f42afad9907c.png)

I am in Python 3.10.6. 

Thanks,
Savino

**Comment by pjaselin** [comment]
Hi Savino and thanks for bringing this to my attention. Out of curiosity, could you share the pip list output? Also could you try upgrading numpy to see if that fixes it? That's just based on my SO search for the error: https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp

**Comment by piccolomo** [comment]
Hi, 
I have no idea why, but I have imported `cubist` with no issues this time. Not sure what happened in the meantime, probably I have installed some new packages, which required the upgrade of `numpy`? Very hard to tell. Anyway I hope it helps anyway.

**Comment by pjaselin** [comment]
Yeah it might be too late for the pip list then and I don't see a reason for an older numpy version to have been installed. Maybe another package requested an older one? I'm also not sure if this comes from some dependency between cython and numpy. I could catch the error on import and suggest trying to update numpy though. Glad it works now!
