### ISSUE TITLE
Error Installing with Python 3.11

### ISSUE THREAD

**Issue by lheberling** [pjaselin/Cubist#121]
Hi,

I received the following error when attempting to pip install cubist on python 3.11.5: 
cubist/src\utility.c(33): fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory

Would anyone possibly know how to address this error? Or has anyone had success with pip installing cubist with python 3.11? I performed the C++ compiler installation via https://wiki.python.org/moin/WindowsCompilers#Microsoft_Visual_C.2B-.2B-_14.2_standalone:_Build_Tools_for_Visual_Studio_2019_.28x86.2C_x64.2C_ARM.2C_ARM64.29

Thanks!

**Comment by pjaselin** [comment]
Hi @lheberling, I just tried this out and I can confirm that pip installing in a 3.10 environment works but not for 3.11 for some reason. I don't know why that's going on given testing passed back in March. I don't have a ton of free time right now but I'll look into this when I can.

**Comment by a98233** [comment]
I've met the same error when installing on the python 3.11.5. But I can successfully install it on python 3.6.15. Maybe other guys can install it on the previous version of python to use this package until this bug is fixed.

**Comment by pjaselin** [comment]
Update: It looks like installing on Windows + 3.11 uses the tar.gz instead of a whl. Looking at the cibuildwheels GitHub action, the pinned version only supports up to CPython 3.10. So the fix is likely simply using the latest cibuildwheels action. I might look at mimicking NumPy's build pattern. Thanks for raising this @lheberling!

**Comment by pjaselin** [comment]
@lheberling and @a98233. I fixed this with 0.1.1. Thanks again for bringing this to my attention!
