### ISSUE TITLE
Access Cubist tree 

### ISSUE THREAD

**Issue by Paulnkk** [pjaselin/Cubist#151]
Hey,

Is it possible to access the tree structure in Cubist so that information about child-parent nodes is available and also rules can be accessed in this tree structure?

Thank you and best regards

Paul

**Comment by pjaselin** [comment]
Hi Paul, what do you mean by that or what are you looking for? The rules are flat and there aren't tree-like hierarchies (or I haven't seen any myself) just rules by committee if you choose to use those. Are you looking to access each rule as a sci-kit learn LinearRegressor class?

**Comment by Paulnkk** [comment]
@pjaselin Thanks for the response! Yes, I was looking for a structure in tree-like hierarchies in order to understand how rules were created from the tree

**Comment by pjaselin** [comment]
You might want to take a look at the verbose output from the model though. It's more of a list of rules, not a tree/hierarchy. It's not doing if rule 1 and rule 2 and rule 3 etc...
