### ISSUE TITLE
The function make_data_string abnormal exit

### ISSUE THREAD

**Issue by JerryVSTom** [pjaselin/Cubist#59]
when use Cubist().score(x,y)， the code runs to /cubist/cubist/(323)make_data_string arise NoneType no copy error,  suggestion add code in make_data_string:
    if y is not None:
        y = y.copy(deep=True)
    else:
        pass

**Comment by pjaselin** [comment]
Hi @JerryVSTom, thanks for the note. I made a change that broke the C code, but I've fixed that in the Feature/add_comments branch. Working on a bunch of changes/tests over there right now. There's a little more involved but you're definitely close on how I fixed this.
