### ISSUE TITLE
Issue In Import cubist in the Google Colab

### ISSUE THREAD

**Issue by khanifar** [pjaselin/Cubist#66]
Hello, 

After installing the _cubist package_ and when importing it in the _Google Colab_, I encounter the following error:

---------------------------------------------------------------------------

> ImportError                               Traceback (most recent call last)
> <ipython-input-2-a73a12756df4> in <module>()
> ----> 1 from cubist import Cubist
> 
> /usr/local/lib/python3.7/dist-packages/cubist/cubist.py in <module>()
>       4 import pandas as pd
>       5 
> ----> 6 from sklearn.utils import _deprecate_positional_args
>       7 from sklearn.utils.validation import check_array, check_is_fitted, \
>       8     check_X_y, check_is_fitted, check_random_state, _check_sample_weight
> 
> ImportError: cannot import name '_deprecate_positional_args' from 'sklearn.utils' (/usr/local/lib/python3.7/dist-packages/sklearn/utils/__init__.py)

---------------------------------------------------------------------------
I also tried the solutions mentioned [here ](https://stackoverflow.com/questions/62641367) but the problem was not solved.

How can this problem be solved?

Thank you so much

**Comment by pjaselin** [comment]
Hey @khanifar thanks for this update. It looks like there were some changes when sklearn went to v1 in how they do ensemble instantiation. I just fixed that in one of the dev branches. Could you try running:
```bash
pip install https://github.com/pjaselin/Cubist/archive/refs/heads/feature/add_comments.zip
```
and let me know if it works for you?

**Comment by khanifar** [comment]
Thank you @pjaselin.

The package was installed and executed well.

For information, after installation, I saw an error in executing the following code:

`from mlxtend.feature_selection import SequentialFeatureSelector as SFS
`
Error : _ModuleNotFoundError: No module named 'sklearn.externals.joblib'_

But this error was fixed by executing the following code:
```
import joblib
import sys
sys.modules['sklearn.externals.joblib'] = joblib
```
Thank you so much.

**Comment by pjaselin** [comment]
Hi @khanifar, thanks for letting me know this fix works. I'll push out an update soon if not tonight. 

Are you using mlxtend in your project? I appreciate the follow up note but I don't believe this package or it's dependencies rely on that. Please let me know if this particular to this package or a local environment issue. Thanks!
