### ISSUE TITLE
Windows support please!

### ISSUE THREAD

**Issue by jwgda** [pjaselin/Cubist#70]
Just a vote for Windows support!  Eager to try this.

**Comment by pjaselin** [comment]
Hey @jwgda! I've been looking into this! Trying to figure out how the R package does it but I'm looking at that as my example. Also need to look at appveyor for it. I'd also definitely recommend using WSL in the meantime!

**Comment by DavidWalz** [comment]
Building wheels for differents OSes also works purely with github actions, see [here](https://github.com/pypa/cibuildwheel) or for an example [here](https://github.com/epfl-lamd/hvwfg/blob/master/.github/workflows/pythonpackage.yml).

**Comment by pjaselin** [comment]
Done

**Comment by DavidWalz** [comment]
Thanks! The latest release 0.0.14 was not published to pypi.
The publish job seems to have been skipped https://github.com/pjaselin/Cubist/actions/runs/1419647932

**Comment by pjaselin** [comment]
@DavidWalz Yeah I was still trying to figure out how to handle the GitHub actions builds with Cython dependencies. I actually had to use the win32ports scripts to fix the sys/time issues for windows. Looks like it works now!
